# App Engine deployment configuration
runtime: nodejs18

env_variables:
  NODE_ENV: production
  PORT: 8080
  TFJS_BACKEND: cpu
  TFJS_DISABLE_WEBGL: true

automatic_scaling:
  min_instances: 0
  max_instances: 10
