steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "Dockerfile.backend"
      - "-t"
      - "gcr.io/$PROJECT_ID/stock-trading-backend:latest"
      - "."

  # Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/stock-trading-backend:latest"

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "stock-trading-backend-v3"
      - "--image=gcr.io/$PROJECT_ID/stock-trading-backend:latest"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--memory=2Gi"
      - "--cpu=2"
      - "--port=8080"
      - "--set-env-vars=NODE_ENV=production"

timeout: 1200s
options:
  machineType: "E2_HIGHCPU_8"
