# Cloud Build configuration for Stock Trading App
steps:
  # Step 1: Build the application using the standard Dockerfile
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/stock-trading-app:$BUILD_ID",
        "-t",
        "gcr.io/$PROJECT_ID/stock-trading-app:latest",
        "-f",
        "Dockerfile",
        ".",
        "--build-arg",
        "NODE_ENV=production",
      ]
    timeout: "2400s"

  # Step 2: Push the image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/stock-trading-app:$BUILD_ID"]
    timeout: "900s"

  # Step 3: Push the latest tag
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/stock-trading-app:latest"]
    timeout: "900s"

  # Step 4: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "stock-trading-app",
        "--image",
        "gcr.io/$PROJECT_ID/stock-trading-app:$BUILD_ID",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8000",
        "--memory",
        "4Gi",
        "--cpu",
        "2",
        "--timeout",
        "900",
        "--concurrency",
        "50",
        "--min-instances",
        "0",
        "--max-instances",
        "2",
        "--set-env-vars",
        "NODE_ENV=production,PORT=8000,TFJS_BACKEND=cpu,TFJS_DISABLE_WEBGL=true,CLOUD_SQL_CONNECTION_NAME=$PROJECT_ID:us-central1:stocktrading-mysql",
        "--set-secrets",
        "DATABASE_HOST=database-host:latest,DATABASE_PORT=database-port:latest,DATABASE_USERNAME=database-username:latest,DATABASE_PASSWORD=database-password:latest,DATABASE_NAME=database-name:latest,DB_USERNAME=db-username:latest,DB_PASSWORD=db-password:latest,DB_NAME=db-name:latest",
        "--add-cloudsql-instances",
        "$PROJECT_ID:us-central1:stocktrading-mysql",
      ]
    timeout: "600s"

# Substitution variables
substitutions:
  _REGION: "us-central1"

# Build options
options:
  machineType: "E2_HIGHCPU_8"
  diskSizeGb: "100"
  logging: "CLOUD_LOGGING_ONLY"
  substitution_option: "ALLOW_LOOSE"
  env:
    - "NODE_ENV=production"
    - "TFJS_BACKEND=cpu"
    - "TFJS_DISABLE_WEBGL=true"

# Build timeout
timeout: "3600s"

# Images to be stored in Container Registry
images:
  - "gcr.io/$PROJECT_ID/stock-trading-app:$BUILD_ID"
  - "gcr.io/$PROJECT_ID/stock-trading-app:latest"
