# Simple Cloud Build configuration for debugging
steps:
  # Step 1: Build the application
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/stock-trading-app:$BUILD_ID",
        "-t",
        "gcr.io/$PROJECT_ID/stock-trading-app:latest",
        "-f",
        "Dockerfile",
        ".",
      ]
    timeout: "1800s"

  # Step 2: Push the image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/stock-trading-app:$BUILD_ID"]
    timeout: "600s"

  # Step 3: Deploy to Cloud Run (simplified)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "stock-trading-app",
        "--image",
        "gcr.io/$PROJECT_ID/stock-trading-app:$BUILD_ID",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8000",
        "--memory",
        "4Gi",
        "--cpu",
        "2",
        "--timeout",
        "900",
        "--set-env-vars",
        "NODE_ENV=production,PORT=8000",
      ]
    timeout: "600s"

# Build options
options:
  machineType: "E2_HIGHCPU_8"
  diskSizeGb: "100"
  logging: "CLOUD_LOGGING_ONLY"

# Build timeout
timeout: "2400s"

# Images to be stored in Container Registry
images:
  - "gcr.io/$PROJECT_ID/stock-trading-app:$BUILD_ID"
  - "gcr.io/$PROJECT_ID/stock-trading-app:latest"
