import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faBackward,
  faBalanceScale,
  faBell,
  // Portfolio and trading specific
  faBriefcase,
  faCalculator,
  faCalendar,
  faCaretDown,
  faCaretRight,
  faCaretUp,
  faChartArea,
  faChartBar,
  // Trading and finance icons
  faChartLine,
  faChartPie,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  // Status and indicators
  faCircle,
  faClock,
  faCog,
  faCoins,
  faCopy,
  faCreditCard,
  // Data and analytics
  faDatabase,
  faDollarSign,
  faDownload,
  faEdit,
  faExchangeAlt,
  faExclamationTriangle,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faFastForward,
  faFileAlt,
  faFileExport,
  faFileImport,
  faFilter,
  faFolder,
  faFolderOpen,
  faGavel,
  faHandHoldingUsd,
  faHandshake,
  // Navigation and UI icons
  faHome,
  // Empty states and messages
  faInbox,
  faInfoCircle,
  faLink,
  faLongArrowAltDown,
  // Trends and movements
  faLongArrowAltUp,
  faMinus,
  faMoneyBillWave,
  faPause,
  faPercentage,
  faPiggyBank,
  // General UI
  faPlay,
  faPlus,
  faRandom,
  faRefresh,
  faRetweet,
  faSave,
  faSearch,
  faShare,
  faSignOutAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSpinner,
  // Additional icons
  faSquare,
  faStop,
  faTable,
  faTimes,
  faTrash,
  faUpload,
  faUser,
  faWallet,
} from "@fortawesome/free-solid-svg-icons";

// Add icons to the library
library.add(
  // Trading and finance
  faChartLine,
  faChartArea,
  faChartBar,
  faChartPie,
  faDollarSign,
  faCoins,
  faWallet,
  faCreditCard,
  faMoneyBillWave,
  faHandHoldingUsd,
  faExchangeAlt,
  faPiggyBank,

  // Navigation and UI
  faHome,
  faSearch,
  faCog,
  faUser,
  faBell,
  faSignOutAlt,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faChevronUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faTimes,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faSave,
  faRefresh,

  // Status and indicators
  faCircle,
  faCheckCircle,
  faExclamationTriangle,
  faInfoCircle,
  faSpinner,
  faClock,
  faCalendar,
  faEye,
  faEyeSlash,
  // Trends and movements
  faLongArrowAltUp,
  faLongArrowAltDown,
  faCaretUp,
  faCaretDown,

  // Data and analytics
  faDatabase,
  faTable,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faDownload,
  faUpload,
  faFileExport,
  faFileImport,

  // Portfolio and trading specific
  faBriefcase,
  faBalanceScale,
  faPercentage,
  faCalculator,
  faGavel,
  faHandshake,

  // General UI
  faPlay,
  faPause,
  faStop,
  faFastForward,
  faBackward,
  faRandom,
  faRetweet,
  faShare,
  faCopy,
  faLink,
  faExternalLinkAlt,
  // Empty states and messages
  faInbox,
  faFolder,
  faFolderOpen,
  faFileAlt,

  // Additional icons
  faSquare,
  faCaretRight
);

// Export commonly used icon names for easy reference
export const IconNames = {
  // Trading and finance
  CHART_LINE: "chart-line",
  CHART_AREA: "chart-area",
  CHART_BAR: "chart-bar",
  CHART_PIE: "chart-pie",
  DOLLAR_SIGN: "dollar-sign",
  COINS: "coins",
  WALLET: "wallet",
  CREDIT_CARD: "credit-card",
  MONEY_BILL_WAVE: "money-bill-wave",
  HAND_HOLDING_USD: "hand-holding-usd",
  EXCHANGE_ALT: "exchange-alt",
  PIGGY_BANK: "piggy-bank",

  // Navigation and UI
  HOME: "home",
  SEARCH: "search",
  COG: "cog",
  USER: "user",
  BELL: "bell",
  SIGN_OUT_ALT: "sign-out-alt",
  ARROW_LEFT: "arrow-left",
  ARROW_RIGHT: "arrow-right",
  ARROW_UP: "arrow-up",
  ARROW_DOWN: "arrow-down",
  CHEVRON_UP: "chevron-up",
  CHEVRON_DOWN: "chevron-down",
  CHEVRON_LEFT: "chevron-left",
  CHEVRON_RIGHT: "chevron-right",
  TIMES: "times",
  PLUS: "plus",
  MINUS: "minus",
  EDIT: "edit",
  TRASH: "trash",
  SAVE: "save",
  REFRESH: "refresh",

  // Status and indicators
  CIRCLE: "circle",
  CHECK_CIRCLE: "check-circle",
  EXCLAMATION_TRIANGLE: "exclamation-triangle",
  INFO_CIRCLE: "info-circle",
  SPINNER: "spinner",
  CLOCK: "clock",
  CALENDAR: "calendar",
  EYE: "eye",
  EYE_SLASH: "eye-slash",
  // Trends and movements
  LONG_ARROW_ALT_UP: "long-arrow-alt-up",
  LONG_ARROW_ALT_DOWN: "long-arrow-alt-down",
  CARET_UP: "caret-up",
  CARET_DOWN: "caret-down",

  // Data and analytics
  DATABASE: "database",
  TABLE: "table",
  FILTER: "filter",
  SORT: "sort",
  SORT_UP: "sort-up",
  SORT_DOWN: "sort-down",
  DOWNLOAD: "download",
  UPLOAD: "upload",
  FILE_EXPORT: "file-export",
  FILE_IMPORT: "file-import",

  // Portfolio and trading specific
  BRIEFCASE: "briefcase",
  BALANCE_SCALE: "balance-scale",
  PERCENTAGE: "percentage",
  CALCULATOR: "calculator",
  GAVEL: "gavel",
  HANDSHAKE: "handshake",

  // General UI
  PLAY: "play",
  PAUSE: "pause",
  STOP: "stop",
  FAST_FORWARD: "fast-forward",
  BACKWARD: "backward",
  RANDOM: "random",
  RETWEET: "retweet",
  SHARE: "share",
  COPY: "copy",
  LINK: "link",
  EXTERNAL_LINK_ALT: "external-link-alt",
  // Empty states and messages
  INBOX: "inbox",
  FOLDER: "folder",
  FOLDER_OPEN: "folder-open",
  FILE_ALT: "file-alt",

  // Additional icons
  SQUARE: "square",
  CARET_RIGHT: "caret-right",
} as const;
